export function printHelp(version = "0.0.0"): void {
  console.log(
    [
      `tavo CLI v${version}`,
      "",
      "Commands:",
      "  tavo create app [dir]",
      "  tavo dev [--ssr] [--host 0.0.0.0|--network]",
      "  tavo build",
      "  tavo preview [--ssr] [--host 0.0.0.0|--network]",
      "  tavo monitor [--url http://127.0.0.1:4174]",
      "  tavo routes [--json]",
      "  tavo info [--json]",
      "  tavo inventory [--json]",
      "  tavo doctor [--json]",
      "  tavo doctor --fix-dry-run [--json]",
      "  tavo check [--json]",
      "  tavo agent-context --json [--task <task>] [--target <name>] [--detail summary|full]",
      "  tavo inspect <route|component|store|file|api> <target> --json",
      "  tavo inspect plugins [--json]",
      "  tavo change --from-json <file> [--dry-run]",
      "  tavo change --from-stdin [--dry-run]",
      "  tavo verify [--no-project-scripts] [--json]",
      "  tavo verify --smoke --json",
      "  tavo verify --spec <file> --json",
      "  tavo generate page <name> [--loader] [--seo] [--typed-route]",
      "  tavo generate component <name> [--props]",
      "  tavo generate store <name> [--shape key,count]",
      "  tavo generate layout <name>",
      "  tavo generate 404",
      "  tavo generate error",
      "  tavo generate action <name>",
      "  tavo generate --from-json <file>",
      "  tavo generate --from-stdin",
      "  tavo generate --validate-spec <file>",
      "",
      "Flags:",
      "  --force                 overwrite generated files when supported",
      "  --loader                include a typed page loader in page generator output",
      "  --seo                   include Seo metadata in page generator output",
      "  --typed-route           wrap a generated page with defineRoutePage(...)",
      "  --props                 include a typed props example in component generator output",
      "  --shape <keys>          comma-separated store keys for store generator output",
      "  --from-json <file>      generate from a JSON spec file",
      "  --from-stdin            generate from JSON read on stdin",
      "  --validate-spec <file>  validate a generator spec without writing files",
      "  --dry-run               print a transactional generation plan without writing files",
      "  --fix-dry-run           print suggested doctor fixes without editing files",
      "  --fix                   apply low-risk doctor fixes",
      "  --spec <file>           include a generator spec in verify output",
      "  --task <task>           select task-specific agent context",
      "  --detail <level>        select summary or full agent context",
      "  --files <list>          verify comma-separated changed files",
      "  --receipt <file>        verify files listed by a change receipt",
      "  --smoke                 include lightweight route smoke checks in verify output",
      "  --no-project-scripts    skip package scripts during restricted verification",
      "  --package-manager <pm>  scaffold app using npm, pnpm, yarn, or bun",
      "  --report-json           write .tavo/generated/build-report.json",
      "  --max-first-load-js <size>  fail build when initial JS exceeds size (for example 150kb)",
      "  --max-route-js <size>    fail build when route JS exceeds size (for example 40kb)",
      "  --prerender-styles <mode>  choose inline or external styles for static pages",
      "  --once                  print one monitor snapshot and exit",
      "  --json                  print supported command output as JSON",
      "  --interval <ms>         delay between monitor refreshes",
      "  --token <token>         send a monitor authorization bearer token",
      "  --host <ip>             bind dev/preview server to a host, e.g. 0.0.0.0 for LAN access",
      "  --network               shortcut for --host 0.0.0.0",
      "  --debug                 show error stack traces",
      "  --help                  show this message",
      "  --version               print CLI version",
    ].join("\n"),
  );
}
