import {
  Fragment,
  h,
  type Child,
  type ClassName,
  type Component,
  type PropsWithChildren,
  type VNode,
} from "./jsx.js";
import {
  Deferred,
  ErrorBoundary,
  Font,
  Head,
  Image,
  lazy,
  Script,
  Seo,
  createDeferredValue,
  type ErrorBoundaryProps,
  type FontDisplay,
  type FontProps,
  type HeadProps,
  type DeferredProps,
  type DeferredState,
  type DeferredTimeoutError,
  type DeferredValue,
  type ImageFormat,
  type ImageProps,
  type LazyComponent,
  type LazyErrorFallback,
  type LazyErrorState,
  type LazyFallback,
  type LazyLoader,
  type LazyModule,
  type LazyOptions,
  type LazyPendingState,
  type LazyStatus,
  type ScriptProps,
  type SeoOpenGraph,
  type SeoProps,
  type SeoTwitter,
} from "./components/index.js";
import { createRoot, render, type Root } from "./dom.js";
import {
  createListRefs,
  createRef,
  mergeRefs,
  setRef,
  type DomRef,
  type DomRefCallback,
  type DomRefObject,
} from "./refs/index.js";
import {
  autoFocus,
  createDirective,
  transition,
  type ElementCleanup,
  type ElementDirective,
  type ElementDirectiveInput,
  type TransitionClassNames,
  type TransitionOptions,
} from "./elements/index.js";
import {
  captureFocusRestore,
  focusFirst,
  focusFirstInvalid,
  getFocusableElements,
  trapFocus,
} from "./focus/index.js";
import {
  observeIntersection,
  observeMutation,
  observeResize,
  type ElementTarget,
} from "./observers/index.js";
import { renderToString } from "./render/static.js";
import type {
  MvcComponentDefinition,
  TavoAction,
} from "./framework/types.js";
import {
  defineGlobalStore,
  getGlobalStore,
  hasGlobalStore,
  listGlobalStores,
} from "./framework/global-store.js";
import {
  createServiceKey,
  getService,
  hasService,
  listServices,
  registerService,
  tryGetService,
  type RegisterServiceOptions,
  type ServiceIdentifier,
  type ServiceKey,
} from "./framework/services.js";
import {
  createStore,
  createExternalStore,
  computedStore,
  persistStore,
  shallowEqual,
  type ExternalStore,
  type PersistStoreOptions,
  type SelectorListener,
  type StatePatch,
  type StateUpdater,
  type StorageLike,
  type Store,
  type StoreInitializer,
  type StoreInitializerSet,
  type StoreListener,
  type StorePath,
  type StorePathSegment,
  type StoreSelector,
  type StoreWatchListener,
  type Unsubscribe,
} from "./store/index.js";
import {
  DEFAULT_I18N_SERVICE_NAME,
  createI18n,
  defineMessages,
  type AnyI18nService,
  type CreateI18nOptions,
  type DefinedI18nMessages,
  type I18nDetectLocaleInput,
  type I18nLocaleDirection,
  type I18nLocaleInfo,
  type I18nMessages,
  type I18nMissingKeyPayload,
  type I18nParams,
  type I18nPrimitive,
  type I18nResolvedPath,
  type I18nRoutingOptions,
  type I18nService,
  type I18nSetLocaleOptions,
  type I18nState,
  type I18nTextTree,
  type I18nTextValue,
  type I18nTranslationKey,
} from "./i18n/index.js";
import {
  bootTavo,
  getTavoBootMode,
  type BootTavoOptions,
  type BootTavoResult,
  type TavoBootMode,
} from "./auto-pages/bootstrap.js";
import { TavoController, createTavo } from "./framework/mvc.js";
import {
  createStyleRegistry,
  ensureClientStyle,
  getActiveStyleRegistry,
  renderStyleTags,
  style,
  withStyleRegistry,
  type StyleOptions,
  type StyleRegistry,
  type StyleRegistryEntry,
} from "./style.js";
import "./style-imports.js";

export {
  Deferred,
  ErrorBoundary,
  Font,
  Fragment,
  Head,
  Image,
  Script,
  Seo,
  TavoController,
  DEFAULT_I18N_SERVICE_NAME,
  autoFocus,
  captureFocusRestore,
  bootTavo,
  computedStore,
  createDirective,
  createDeferredValue,
  createI18n,
  createListRefs,
  createRef,
  createRoot,
  createServiceKey,
  createStore,
  createExternalStore,
  createStyleRegistry,
  createTavo,
  defineGlobalStore,
  defineMessages,
  focusFirst,
  focusFirstInvalid,
  getGlobalStore,
  getFocusableElements,
  getService,
  getActiveStyleRegistry,
  getTavoBootMode,
  h,
  hasGlobalStore,
  hasService,
  lazy,
  ensureClientStyle,
  listGlobalStores,
  listServices,
  mergeRefs,
  observeIntersection,
  observeMutation,
  observeResize,
  persistStore,
  render,
  renderStyleTags,
  renderToString,
  registerService,
  setRef,
  shallowEqual,
  style,
  trapFocus,
  transition,
  tryGetService,
  withStyleRegistry,
};

export type {
  BootTavoOptions,
  BootTavoResult,
  Child,
  ClassName,
  Component,
  DeferredProps,
  DeferredState,
  DeferredTimeoutError,
  DeferredValue,
  DefinedI18nMessages,
  DomRef,
  DomRefCallback,
  DomRefObject,
  ElementCleanup,
  ElementDirective,
  ElementDirectiveInput,
  ElementTarget,
  ErrorBoundaryProps,
  ExternalStore,
  FontDisplay,
  FontProps,
  HeadProps,
  CreateI18nOptions,
  I18nMessages,
  AnyI18nService,
  I18nDetectLocaleInput,
  I18nLocaleDirection,
  I18nLocaleInfo,
  I18nMissingKeyPayload,
  I18nParams,
  I18nPrimitive,
  I18nResolvedPath,
  I18nRoutingOptions,
  I18nService,
  I18nSetLocaleOptions,
  I18nState,
  I18nTextTree,
  I18nTextValue,
  I18nTranslationKey,
  ImageFormat,
  ImageProps,
  LazyComponent,
  LazyErrorFallback,
  LazyErrorState,
  LazyFallback,
  LazyLoader,
  LazyModule,
  LazyOptions,
  LazyPendingState,
  LazyStatus,
  ScriptProps,
  SeoOpenGraph,
  SeoProps,
  SeoTwitter,
  MvcComponentDefinition,
  TavoAction,
  PropsWithChildren,
  PersistStoreOptions,
  Root,
  SelectorListener,
  RegisterServiceOptions,
  ServiceIdentifier,
  ServiceKey,
  StatePatch,
  StateUpdater,
  StorageLike,
  Store,
  StoreInitializer,
  StoreInitializerSet,
  StoreListener,
  StorePath,
  StorePathSegment,
  StoreSelector,
  StoreWatchListener,
  StyleOptions,
  StyleRegistry,
  StyleRegistryEntry,
  TavoBootMode,
  TransitionClassNames,
  TransitionOptions,
  Unsubscribe,
  VNode,
};
export {
  createAction,
  type Action,
  type ActionContext,
  type ActionState,
  type ActionStatus,
} from "./actions/index.js";
export * from "./diagnostics.js";
export * from "./dom.js";
export * from "./focus/index.js";
export * from "./forms/index.js";
export * from "./observers/index.js";
export * from "./resources/index.js";
export * from "./stability.js";
