// Generated by scripts/generate-agent-api-cards.mjs. Do not edit by hand.
export const GENERATED_API_SIGNATURES: Record<string, string> = {
  "defineRoutePage": "<TPath extends string, TData = unknown>(path: TPath, page: TypedPageModule<TPath, TData>): TypedPageModule<TPath, TData>",
  "createTavo": "<P extends AnyRecord, S extends AnyRecord, C = unknown>(definition: MvcComponentDefinition<P, S, C>): Component<P>",
  "defineGlobalStore": "<T extends AnyRecord>(name: string, initialState: T | StoreInitializer<T>): Store<T>",
  "defineValidatedAction": "<TInput>(schema: TavoSchema<TInput>, handler: (context: ValidatedActionContext<TInput>) => Response | ActionResult | void | Promise<Response | ActionResult | void>, options?: PageActionOptions): PageAction",
  "Seo": "(props: SeoProps): Child"
};
